package com.asia.entity

import org.jetbrains.exposed.dao.id.IntIdTable
import org.jetbrains.exposed.sql.Column

object UserTable : IntIdTable("users") {
    val coreId: Column<Int> = integer("core_id").default(0)
    val username: Column<String> = varchar("username", 64)
    val email: Column<String> = varchar("email", 64)
    val lastLoginDate: Column<Int> = integer("last_login_date").default(0)
    val firstname: Column<String> = varchar("firstname", 32).default("")
    val firstnamePinyin: Column<String> = varchar("firstname_pinyin", 128).default("")
    val lastname: Column<String> = varchar("lastname", 32).default("")
    val lastnamePinyin: Column<String> = varchar("lastname_pinyin", 128).default("")
    val tel: Column<String> = varchar("tel", 32).default("")
    val sysPerm: Column<Int> = integer("sysperm").default(0)
    val perf: Column<Int> = integer("perf").default(0)
    val enabled: Column<Int> = integer("enabled").default(1)
    val teamId: Column<Int?> = integer("team_id").nullable()
    val businessTeamId: Column<Int?> = integer("business_team_id").nullable()
    val supervisorId: Column<Int?> = integer("supervisor_id").nullable()
    val dateJoined: Column<Int> = integer("date_joined").default(0)
    val dateGraduated: Column<Int> = integer("date_graduated").default(0)
    val dateQuit: Column<Int> = integer("date_quit").default(0)
    val companyId: Column<String> = varchar("company_id", 16).default("")
    val attendanceId: Column<String> = varchar("attendance_id", 16).default("")
    val isInternship: Column<Short> = short("is_internship").default(-1)
    val dateStarted: Column<Int> = integer("date_started").default(0)
    val fullName: Column<String> = varchar("fullname", 64).default("")
    val isGuest: Column<Short> = short("is_guest").default(0)
    val dingTalk: Column<String?> = varchar("dingtalk", 64).nullable()
    val firstSchedule: Column<Int> = integer("first_schedule").default(1)
    val isAbsent: Column<Int> = integer("is_absent").default(-1)
    val fullNameFirstLetter: Column<String> = varchar("fullname_first_letter", 64)
    val createAt: Column<Int> = integer("create_at")
    val avatar: Column<String?> = varchar("avatar", 256).nullable()
    val director: Column<Int> = integer("director").default(0)
    val sex: Column<Short> = short("sex").default(0)
    val jobStatus: Column<Short> = short("job_status").default(-1)
    val employeeStatus: Column<Short> = short("employeeStatus").default(-1)
    val assetStatus: Column<Short> = short("assert_status").default(1)
    val emailStatus: Column<Short> = short("short_status").default(0)
    val itStatus: Column<Short> = short("it_status").default(0)
    val toCompanyTime: Column<Int> = integer("to_company_time").default(0)
    val createdUid: Column<Int> = integer("created_uid").default(0)
    val cancelJoin: Column<Byte> = byte("cancel_join").default(0)
    val hrbpUid: Column<Int> = integer("hrbp_uid").default(0)
    val baseInfo: Column<Int?> = integer("baseInfo").nullable()
    val staffJoinNotice: Column<Int> = integer("staffJoinNotice")
    val sysPermSecond: Column<Int> = integer("sysperm_second").default(0)
    val feishu: Column<String?> = varchar("feishu", 20).nullable()
}
